### ISSUE TITLE
Can't send email with AmazonSES at version after 2.0

### ISSUE THREAD

**Issue by PhongGCS** [byjg/mailwrapper#11]
I install byjg/mailwrapper: 2.0.5 currently
I got this error

> Fatal error: Uncaught exception 'Aws\Ses\Exception\SesException' with message 'Error executing "SendRawEmail" on "https://email.eu-west-1.amazonaws.com"; AWS HTTP error: Client error: 'POST https://email.eu-west-1.amazonaws.com' resulted in a '400 Bad Request' response: <ErrorResponse xmlns="http://ses.amazonaws.com/doc/2010-12-01/"> <Error> <Type>Sender</Type> <Code>InvalidPara (truncated...) InvalidParameterValue (client): Duplicate header 'Content-Type'. - <ErrorResponse xmlns="http://ses.amazonaws.com/doc/2010-12-01/"> <Error> <Type>Sender</Type> <Code>InvalidParameterValue</Code> <Message>Duplicate header 'Content-Type'.</Message> </Error> <RequestId>0cc4dd5c-2e9b-4116-acf7-76948bfe8d0e</RequestId> </ErrorResponse> ' GuzzleHttp\Exception\ClientException: Client error: 'POST https://email.eu-west-1.amazonaws.com' resulted in /Applications/MAMP/htdocs/test/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php on line 195
> Aws\Ses\Exception\SesException: Error executing "SendRawEmail" on "https://email.eu-west-1.amazonaws.com"; AWS HTTP error: Client error: 'POST https://email.eu-west-1.amazonaws.com' resulted in a '400 Bad Request' response: <ErrorResponse xmlns="http://ses.amazonaws.com/doc/2010-12-01/"> <Error> <Type>Sender</Type> <Code>InvalidPara (truncated...) InvalidParameterValue (client): Duplicate header 'Content-Type'. - <ErrorResponse xmlns="http://ses.amazonaws.com/doc/2010-12-01/"> <Error> <Type>Sender</Type> <Code>InvalidParameterValue</Code> <Message>Duplicate header 'Content-Type'.</Message> </Error> <RequestId>6327d5e0-5262-4322-b528-312fdaf1f780</RequestId> </ErrorResponse> in /app/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php on line 195

or you can see error image at here https://imgur.com/LUAgKF7

This is my content at  index.php file
`      

        define('ACCESS_KEY', 'key');

        define('SECRET_KEY', 'key');

        define('REGION', 'eu-west-1');

        $mailer =  new \ByJG\Mail\Wrapper\AmazonSesWrapper(

            new \ByJG\Util\Uri(

                'ses://'. ACCESS_KEY. ':' . SECRET_KEY. '@'.REGION

            )

        );

        $envelope = new Envelope();

        $envelope->setFrom('my-email@email.com', 'John Doe');

        $envelope->addTo('clientemail@email.com');

        $envelope->setSubject('Email Subject');

        $envelope->setBody('html text body');

        //  vomit($envelope);

        $mailer->send($envelope);

`

This is composer.json
`
{
    "require": {
        "byjg/mailwrapper": "2.0.*"
    }
}
`

I try to down version byjg/mailwrapper: 2.0.5 to 2.0. I working well.

**Comment by byjg** [comment]
I downgrade the PHPMailer because probably that is the root cause. 

Before I create a new version do you mind in the test in your project by changing your composer.json to:

```
{ "require": { "byjg/mailwrapper": "dev-issue-1" } }
```

Let me know if it worked for you.

**Comment by PhongGCS** [comment]
Thank you, i did as what you said and it works! much appreciate your help.

**Comment by byjg** [comment]
I created the release 2.0.6. 

Thank you.
